name: Publish vue3-ui-lib

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: install Yarn
      run: |
        npm install --global yarn
    - name: Build
      run: |
        yarn install
        yarn run build
  
